spring.application.name=realworld-spring

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:8095/app
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Disable Hibernate DDL Auto-Generation (Hand over schema ownership to Flyway)
spring.jpa.hibernate.ddl-auto=none

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# json formatting, wrap entities in a root field for outgoing data,
# and unwrap the incoming data.
spring.jackson.serialization.wrap_root_value=true
spring.jackson.deserialization.unwrap-root-value=true
